name: CI
on: 
  push:
    branches: [ master ]

jobs: 
  standard-checks:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packages
        run: run ci
      - name: Bundle and Output
        run: npm run build